version: 0.2

env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing some packages and source NPM dependencies...
      - npm install
      - npm update
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 rm --recursive "s3://uway/"
      # - aws cloudfront create-invalidation --distribution-id E2INBLFRZE5LY3 --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: ./build